# *
SharedProperties:
  BackgroundColor: "#FF0000" # Default background color for shared properties

# Selectors

Select:
  - at: "Body"
    backgroundColor: "#FFF00F"
    width: 20px
    height: 30px

