# *
SharedProperties:
  BackgroundColor: "#FF0000" # Default background color for shared properties

# Selectors

Select:

  - at: "Body"
    childrenPlacement: CHILD_DECIDE

  - at: "Label"
    textColor: "#000000"
    lineHeight: 16px

  - at: "Column"
    backgroundImage: url.assets/textures/gui/Column.png
    width: 32px
    height: 32px


