SharedProperties:
  BackgroundColor: "#FF0000"

Select:
  - at: "FreeElement"
    # backgroundImage: "assets/textures/gui/Button.png" ! NOT WORKS
    width: "32px"
    border: "1px #5DE2E7"
    border-left: "5px #FFFFFF"
    globalx: 200
    globaly: 20
    disposition: manual
    childrenPlacement: CHILD_DECIDE

#  - At: "TextField"
#    Width: "200px"
#    Height: "200px"

#  - At: "Body > TextField"
#    BackgroundColor:  "#FF0FF0"

