# *
SharedProperties:
  BackgroundColor: "#FF0000" # Default background color for shared properties

# Selectors

Select:
  - at: "#test"
    backgroundColor: "#FFFFFF"
    width: "16px"
    height: "16px"
    globaly: 16
    globalx: 90

  - at: ".group"
    width: "16px"
    height: "16px"
    backgroundColor: "#00FF00"
    globalx: 0
    globaly: 64
    childrenPlacement: CENTER
    selfDisposition: NONE


  - at: "#test2"
    width: "800px"
    height: "8px"
    backgroundColor: "#FF00FF"


