# *
SharedProperties:
  BackgroundColor: "#FF0000" # Default background color for shared properties

# Selectors

Select:
  - at: "Body"
    childrenPlacement: CHILD_DECIDE

  - at: "Panel"
    backgroundImage: url.assets/textures/gui/Panel.png
    lengthX: 3
    lengthY: 3
    tileSize: 32px

  - at: "Label"
    textColor: "#000000"
    lineHeight: 16px

  - at: "ScrollBar"
    backgroundImage: url.assets/textures/gui/ScrollBar.png
    width: 3px
    height: 3px
