# *
SharedProperties:
  BackgroundColor: "#FF0000" # Default background color for shared properties

# Selectors

Select:
  - at: Body
    childrenPlacement: CHILD_DECIDE
    width: 100%
    height: 100%

  - at: Panel
    backgroundImage: /assets/textures/gui/themes/default/SmallTinyPanel.png
    lengthX: 3
    lengthY: 3
    tileSize: 4px

  - at: Label
    textColor: "#000000"
    lineHeight: 16px

  - at: ScrollBar
    backgroundImage: /assets/textures/gui/themes/default/ScrollBar.png
    width: 3px
    height: 3px
    scrollBarLength: 6
    localX: -50
    direction: vertically

  - at: Slot
    backgroundImage: /assets/textures/gui/themes/default/Slot.png
    width: 20px
    height: 20px

  - at: DraggableElement
    backgroundColor: "#FFFFFF"
    width: 30px
    height: 30px

  - at: ProgressBar
    backgroundImage: /assets/textures/gui/themes/default/incompleteBar.png
    progressBarFullBackground: /assets/textures/gui/themes/default/completeBar.png
    progressBarSmoothingFactor: 0.1
    width: 47px
    height: 5px
