SharedProperties:
  BackgroundColor: "#FF0000"

Select:
  - At: "FreeElement"
    BackgroundColor: "#FF0000"

  - At: "TextField"
    Width: "200px"
    Height: "200px"

  - At: "Body > TextField"
    BackgroundColor:  "#FF0FF0"
